export {
  CitizenDashboardPage,
  CitizenReportCreateWorkspacePage,
  CitizenWorkspacePage,
  DirectorHomePage,
  GuestHomePage,
  InboxCreateWorkspacePage,
  InboxSubjectDetailWorkspacePage,
  InboxWorkspacePage,
  InvestigationDetailWorkspacePage,
  InvestigationsWorkspacePage,
  JournalistWorkspacePage,
  NotificationDetailWorkspacePage,
  NotificationsWorkspacePage,
  PeopleManagementPage,
  PublicationCorrectionsWorkspacePage,
  PublicationDetailWorkspacePage,
  PublicationsWorkspacePage,
  ReportDetailWorkspacePage,
  ReportsWorkspacePage,
  RoleAwareDashboardPage,
  UserCreateWorkspacePage,
  UserStatusWorkspacePage,
  WatcherApplicationsReviewPage,
  WatcherWorkspacePage,
} from './domain-workspaces-legacy'
