const domainLabelByValue: Record<string, string> = {
  ACTIVE: 'Actif',
  ALERT: 'Alerte',
  APPROVED: 'Approuvé',
  ARCHIVED: 'Archivé',
  ARCHIVED_PUBLICATION: 'Publication archivée',
  AUDIO: 'Audio',
  AUTHORITY_STATEMENT: "Déclaration d'autorité",
  BANNED: 'Banni',
  CANCELED: 'Annulé',
  CITIZEN_REPORT: 'Signalement citoyen',
  CONTEXT_COLLAPSE: 'Contexte déplacé',
  CORRECTION: 'Correctif',
  DIRECTOR_INITIATED: 'Créé par la direction',
  DIRECT_EVIDENCE: 'Preuve directe',
  DISABLED: 'Désactivé',
  FABRICATED: 'Fabriqué',
  FALSE: 'Faux',
  IMAGE: 'Image',
  IMPOSTOR: 'Usurpation',
  IN_PROGRESS: 'En enquête',
  JOURNALIST_PROOF: 'Preuve journaliste',
  MANIPULATED: 'Manipulé',
  MEDIA_CROSSCHECK: 'Recoupement média',
  MISLEADING: 'Trompeur',
  NEEDS_REVISION: 'À corriger',
  OFFICIAL_DECREE: 'Décision officielle',
  OPEN: 'Ouvert',
  OTHER: 'Autre',
  PENDING: 'En attente',
  PENDING_REVIEW: 'Revue direction',
  PUBLICATION: 'Publication',
  PUBLISHED: 'Publié',
  REJECTED: 'Rejeté',
  SATIRE: 'Satire',
  TEXT: 'Texte',
  TRUE: 'Vrai',
  UNVERIFIABLE: 'Non vérifiable',
  VIDEO: 'Vidéo',
}

export function domainLabel(value: string) {
  return domainLabelByValue[value] ?? value
}
