/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatcherApplicationsRouteImport } from './routes/watcher-applications'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as JournalistsRouteImport } from './routes/journalists'
import { Route as JournalistRouteImport } from './routes/journalist'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as InboxSubjectsRouteImport } from './routes/inbox-subjects'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsCreateRouteImport } from './routes/reports.create'
import { Route as PublicationsListRouteImport } from './routes/publications.list'
import { Route as PublicationsCorrectionsRouteImport } from './routes/publications.corrections'
import { Route as PublicationsPublicationIdRouteImport } from './routes/publications.$publicationId'
import { Route as JournalistsStatusRouteImport } from './routes/journalists.status'
import { Route as JournalistsListRouteImport } from './routes/journalists.list'
import { Route as JournalistsCreateRouteImport } from './routes/journalists.create'
import { Route as InvestigationsPublishedRouteImport } from './routes/investigations.published'
import { Route as InvestigationsPendingReviewRouteImport } from './routes/investigations.pending-review'
import { Route as InvestigationsInvestigationIdRouteImport } from './routes/investigations.$investigationId'
import { Route as InboxSubjectsReportsRouteImport } from './routes/inbox-subjects.reports'
import { Route as InboxSubjectsGlobalRouteImport } from './routes/inbox-subjects.global'
import { Route as InboxSubjectsCreateRouteImport } from './routes/inbox-subjects.create'

const WatcherApplicationsRoute = WatcherApplicationsRouteImport.update({
  id: '/watcher-applications',
  path: '/watcher-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalistsRoute = JournalistsRouteImport.update({
  id: '/journalists',
  path: '/journalists',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalistRoute = JournalistRouteImport.update({
  id: '/journalist',
  path: '/journalist',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxSubjectsRoute = InboxSubjectsRouteImport.update({
  id: '/inbox-subjects',
  path: '/inbox-subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCreateRoute = ReportsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ReportsRoute,
} as any)
const PublicationsListRoute = PublicationsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsCorrectionsRoute = PublicationsCorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => PublicationsRoute,
} as any)
const PublicationsPublicationIdRoute =
  PublicationsPublicationIdRouteImport.update({
    id: '/$publicationId',
    path: '/$publicationId',
    getParentRoute: () => PublicationsRoute,
  } as any)
const JournalistsStatusRoute = JournalistsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => JournalistsRoute,
} as any)
const JournalistsListRoute = JournalistsListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => JournalistsRoute,
} as any)
const JournalistsCreateRoute = JournalistsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => JournalistsRoute,
} as any)
const InvestigationsPublishedRoute = InvestigationsPublishedRouteImport.update({
  id: '/published',
  path: '/published',
  getParentRoute: () => InvestigationsRoute,
} as any)
const InvestigationsPendingReviewRoute =
  InvestigationsPendingReviewRouteImport.update({
    id: '/pending-review',
    path: '/pending-review',
    getParentRoute: () => InvestigationsRoute,
  } as any)
const InvestigationsInvestigationIdRoute =
  InvestigationsInvestigationIdRouteImport.update({
    id: '/$investigationId',
    path: '/$investigationId',
    getParentRoute: () => InvestigationsRoute,
  } as any)
const InboxSubjectsReportsRoute = InboxSubjectsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => InboxSubjectsRoute,
} as any)
const InboxSubjectsGlobalRoute = InboxSubjectsGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => InboxSubjectsRoute,
} as any)
const InboxSubjectsCreateRoute = InboxSubjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => InboxSubjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citizen': typeof CitizenRoute
  '/dashboard': typeof DashboardRoute
  '/inbox-subjects': typeof InboxSubjectsRouteWithChildren
  '/investigations': typeof InvestigationsRouteWithChildren
  '/journalist': typeof JournalistRoute
  '/journalists': typeof JournalistsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/publications': typeof PublicationsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/watcher-applications': typeof WatcherApplicationsRoute
  '/inbox-subjects/create': typeof InboxSubjectsCreateRoute
  '/inbox-subjects/global': typeof InboxSubjectsGlobalRoute
  '/inbox-subjects/reports': typeof InboxSubjectsReportsRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/investigations/pending-review': typeof InvestigationsPendingReviewRoute
  '/investigations/published': typeof InvestigationsPublishedRoute
  '/journalists/create': typeof JournalistsCreateRoute
  '/journalists/list': typeof JournalistsListRoute
  '/journalists/status': typeof JournalistsStatusRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/publications/corrections': typeof PublicationsCorrectionsRoute
  '/publications/list': typeof PublicationsListRoute
  '/reports/create': typeof ReportsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citizen': typeof CitizenRoute
  '/dashboard': typeof DashboardRoute
  '/inbox-subjects': typeof InboxSubjectsRouteWithChildren
  '/investigations': typeof InvestigationsRouteWithChildren
  '/journalist': typeof JournalistRoute
  '/journalists': typeof JournalistsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/publications': typeof PublicationsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/watcher-applications': typeof WatcherApplicationsRoute
  '/inbox-subjects/create': typeof InboxSubjectsCreateRoute
  '/inbox-subjects/global': typeof InboxSubjectsGlobalRoute
  '/inbox-subjects/reports': typeof InboxSubjectsReportsRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/investigations/pending-review': typeof InvestigationsPendingReviewRoute
  '/investigations/published': typeof InvestigationsPublishedRoute
  '/journalists/create': typeof JournalistsCreateRoute
  '/journalists/list': typeof JournalistsListRoute
  '/journalists/status': typeof JournalistsStatusRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/publications/corrections': typeof PublicationsCorrectionsRoute
  '/publications/list': typeof PublicationsListRoute
  '/reports/create': typeof ReportsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/citizen': typeof CitizenRoute
  '/dashboard': typeof DashboardRoute
  '/inbox-subjects': typeof InboxSubjectsRouteWithChildren
  '/investigations': typeof InvestigationsRouteWithChildren
  '/journalist': typeof JournalistRoute
  '/journalists': typeof JournalistsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/publications': typeof PublicationsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/watcher-applications': typeof WatcherApplicationsRoute
  '/inbox-subjects/create': typeof InboxSubjectsCreateRoute
  '/inbox-subjects/global': typeof InboxSubjectsGlobalRoute
  '/inbox-subjects/reports': typeof InboxSubjectsReportsRoute
  '/investigations/$investigationId': typeof InvestigationsInvestigationIdRoute
  '/investigations/pending-review': typeof InvestigationsPendingReviewRoute
  '/investigations/published': typeof InvestigationsPublishedRoute
  '/journalists/create': typeof JournalistsCreateRoute
  '/journalists/list': typeof JournalistsListRoute
  '/journalists/status': typeof JournalistsStatusRoute
  '/publications/$publicationId': typeof PublicationsPublicationIdRoute
  '/publications/corrections': typeof PublicationsCorrectionsRoute
  '/publications/list': typeof PublicationsListRoute
  '/reports/create': typeof ReportsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/citizen'
    | '/dashboard'
    | '/inbox-subjects'
    | '/investigations'
    | '/journalist'
    | '/journalists'
    | '/notifications'
    | '/profile'
    | '/publications'
    | '/reports'
    | '/watcher-applications'
    | '/inbox-subjects/create'
    | '/inbox-subjects/global'
    | '/inbox-subjects/reports'
    | '/investigations/$investigationId'
    | '/investigations/pending-review'
    | '/investigations/published'
    | '/journalists/create'
    | '/journalists/list'
    | '/journalists/status'
    | '/publications/$publicationId'
    | '/publications/corrections'
    | '/publications/list'
    | '/reports/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/citizen'
    | '/dashboard'
    | '/inbox-subjects'
    | '/investigations'
    | '/journalist'
    | '/journalists'
    | '/notifications'
    | '/profile'
    | '/publications'
    | '/reports'
    | '/watcher-applications'
    | '/inbox-subjects/create'
    | '/inbox-subjects/global'
    | '/inbox-subjects/reports'
    | '/investigations/$investigationId'
    | '/investigations/pending-review'
    | '/investigations/published'
    | '/journalists/create'
    | '/journalists/list'
    | '/journalists/status'
    | '/publications/$publicationId'
    | '/publications/corrections'
    | '/publications/list'
    | '/reports/create'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/citizen'
    | '/dashboard'
    | '/inbox-subjects'
    | '/investigations'
    | '/journalist'
    | '/journalists'
    | '/notifications'
    | '/profile'
    | '/publications'
    | '/reports'
    | '/watcher-applications'
    | '/inbox-subjects/create'
    | '/inbox-subjects/global'
    | '/inbox-subjects/reports'
    | '/investigations/$investigationId'
    | '/investigations/pending-review'
    | '/investigations/published'
    | '/journalists/create'
    | '/journalists/list'
    | '/journalists/status'
    | '/publications/$publicationId'
    | '/publications/corrections'
    | '/publications/list'
    | '/reports/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CitizenRoute: typeof CitizenRoute
  DashboardRoute: typeof DashboardRoute
  InboxSubjectsRoute: typeof InboxSubjectsRouteWithChildren
  InvestigationsRoute: typeof InvestigationsRouteWithChildren
  JournalistRoute: typeof JournalistRoute
  JournalistsRoute: typeof JournalistsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  PublicationsRoute: typeof PublicationsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  WatcherApplicationsRoute: typeof WatcherApplicationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watcher-applications': {
      id: '/watcher-applications'
      path: '/watcher-applications'
      fullPath: '/watcher-applications'
      preLoaderRoute: typeof WatcherApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journalists': {
      id: '/journalists'
      path: '/journalists'
      fullPath: '/journalists'
      preLoaderRoute: typeof JournalistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journalist': {
      id: '/journalist'
      path: '/journalist'
      fullPath: '/journalist'
      preLoaderRoute: typeof JournalistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox-subjects': {
      id: '/inbox-subjects'
      path: '/inbox-subjects'
      fullPath: '/inbox-subjects'
      preLoaderRoute: typeof InboxSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/create': {
      id: '/reports/create'
      path: '/create'
      fullPath: '/reports/create'
      preLoaderRoute: typeof ReportsCreateRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/publications/list': {
      id: '/publications/list'
      path: '/list'
      fullPath: '/publications/list'
      preLoaderRoute: typeof PublicationsListRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/corrections': {
      id: '/publications/corrections'
      path: '/corrections'
      fullPath: '/publications/corrections'
      preLoaderRoute: typeof PublicationsCorrectionsRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/publications/$publicationId': {
      id: '/publications/$publicationId'
      path: '/$publicationId'
      fullPath: '/publications/$publicationId'
      preLoaderRoute: typeof PublicationsPublicationIdRouteImport
      parentRoute: typeof PublicationsRoute
    }
    '/journalists/status': {
      id: '/journalists/status'
      path: '/status'
      fullPath: '/journalists/status'
      preLoaderRoute: typeof JournalistsStatusRouteImport
      parentRoute: typeof JournalistsRoute
    }
    '/journalists/list': {
      id: '/journalists/list'
      path: '/list'
      fullPath: '/journalists/list'
      preLoaderRoute: typeof JournalistsListRouteImport
      parentRoute: typeof JournalistsRoute
    }
    '/journalists/create': {
      id: '/journalists/create'
      path: '/create'
      fullPath: '/journalists/create'
      preLoaderRoute: typeof JournalistsCreateRouteImport
      parentRoute: typeof JournalistsRoute
    }
    '/investigations/published': {
      id: '/investigations/published'
      path: '/published'
      fullPath: '/investigations/published'
      preLoaderRoute: typeof InvestigationsPublishedRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/investigations/pending-review': {
      id: '/investigations/pending-review'
      path: '/pending-review'
      fullPath: '/investigations/pending-review'
      preLoaderRoute: typeof InvestigationsPendingReviewRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/investigations/$investigationId': {
      id: '/investigations/$investigationId'
      path: '/$investigationId'
      fullPath: '/investigations/$investigationId'
      preLoaderRoute: typeof InvestigationsInvestigationIdRouteImport
      parentRoute: typeof InvestigationsRoute
    }
    '/inbox-subjects/reports': {
      id: '/inbox-subjects/reports'
      path: '/reports'
      fullPath: '/inbox-subjects/reports'
      preLoaderRoute: typeof InboxSubjectsReportsRouteImport
      parentRoute: typeof InboxSubjectsRoute
    }
    '/inbox-subjects/global': {
      id: '/inbox-subjects/global'
      path: '/global'
      fullPath: '/inbox-subjects/global'
      preLoaderRoute: typeof InboxSubjectsGlobalRouteImport
      parentRoute: typeof InboxSubjectsRoute
    }
    '/inbox-subjects/create': {
      id: '/inbox-subjects/create'
      path: '/create'
      fullPath: '/inbox-subjects/create'
      preLoaderRoute: typeof InboxSubjectsCreateRouteImport
      parentRoute: typeof InboxSubjectsRoute
    }
  }
}

interface InboxSubjectsRouteChildren {
  InboxSubjectsCreateRoute: typeof InboxSubjectsCreateRoute
  InboxSubjectsGlobalRoute: typeof InboxSubjectsGlobalRoute
  InboxSubjectsReportsRoute: typeof InboxSubjectsReportsRoute
}

const InboxSubjectsRouteChildren: InboxSubjectsRouteChildren = {
  InboxSubjectsCreateRoute: InboxSubjectsCreateRoute,
  InboxSubjectsGlobalRoute: InboxSubjectsGlobalRoute,
  InboxSubjectsReportsRoute: InboxSubjectsReportsRoute,
}

const InboxSubjectsRouteWithChildren = InboxSubjectsRoute._addFileChildren(
  InboxSubjectsRouteChildren,
)

interface InvestigationsRouteChildren {
  InvestigationsInvestigationIdRoute: typeof InvestigationsInvestigationIdRoute
  InvestigationsPendingReviewRoute: typeof InvestigationsPendingReviewRoute
  InvestigationsPublishedRoute: typeof InvestigationsPublishedRoute
}

const InvestigationsRouteChildren: InvestigationsRouteChildren = {
  InvestigationsInvestigationIdRoute: InvestigationsInvestigationIdRoute,
  InvestigationsPendingReviewRoute: InvestigationsPendingReviewRoute,
  InvestigationsPublishedRoute: InvestigationsPublishedRoute,
}

const InvestigationsRouteWithChildren = InvestigationsRoute._addFileChildren(
  InvestigationsRouteChildren,
)

interface JournalistsRouteChildren {
  JournalistsCreateRoute: typeof JournalistsCreateRoute
  JournalistsListRoute: typeof JournalistsListRoute
  JournalistsStatusRoute: typeof JournalistsStatusRoute
}

const JournalistsRouteChildren: JournalistsRouteChildren = {
  JournalistsCreateRoute: JournalistsCreateRoute,
  JournalistsListRoute: JournalistsListRoute,
  JournalistsStatusRoute: JournalistsStatusRoute,
}

const JournalistsRouteWithChildren = JournalistsRoute._addFileChildren(
  JournalistsRouteChildren,
)

interface PublicationsRouteChildren {
  PublicationsPublicationIdRoute: typeof PublicationsPublicationIdRoute
  PublicationsCorrectionsRoute: typeof PublicationsCorrectionsRoute
  PublicationsListRoute: typeof PublicationsListRoute
}

const PublicationsRouteChildren: PublicationsRouteChildren = {
  PublicationsPublicationIdRoute: PublicationsPublicationIdRoute,
  PublicationsCorrectionsRoute: PublicationsCorrectionsRoute,
  PublicationsListRoute: PublicationsListRoute,
}

const PublicationsRouteWithChildren = PublicationsRoute._addFileChildren(
  PublicationsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsCreateRoute: typeof ReportsCreateRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsCreateRoute: ReportsCreateRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CitizenRoute: CitizenRoute,
  DashboardRoute: DashboardRoute,
  InboxSubjectsRoute: InboxSubjectsRouteWithChildren,
  InvestigationsRoute: InvestigationsRouteWithChildren,
  JournalistRoute: JournalistRoute,
  JournalistsRoute: JournalistsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  PublicationsRoute: PublicationsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  WatcherApplicationsRoute: WatcherApplicationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
